### ISSUE TITLE
Error when running script setup_smrt23.sh

### ISSUE THREAD

**Issue by yoann-dufresne** [bioinform/longislnd#38]
I'm trying to use longislnd on examples from your webpage.
As you explain, I need to install smartanalysis first.
But using your script I encounter the following error(s) :

```bash
Creating the user.smrtpipe.rc file...  
ERROR:root:code for hash md5 was not found.  
Traceback (most recent call last):  
  File "/home/yoann/Softwares/longislnd/sampling_example/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/hashlib.py", line 139, in <module>  
    globals()[__func_name] = __get_hash(__func_name)  
  File "/home/yoann/Softwares/longislnd/sampling_example/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor  
    raise ValueError('unsupported hash type %s' % name)  
ValueError: unsupported hash type md5  
ERROR:root:code for hash sha1 was not found.  
Traceback (most recent call last):  
  File "/home/yoann/Softwares/longislnd/sampling_example/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/hashlib.py", line 139, in <module>  
    globals()[__func_name] = __get_hash(__func_name)  
  File "/home/yoann/Softwares/longislnd/sampling_example/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor  
    raise ValueError('unsupported hash type %s' % name)  
ValueError: unsupported hash type sha1  
ERROR:root:code for hash sha224 was not found.  
Traceback (most recent call last):  
  File "/home/yoann/Softwares/longislnd/sampling_example/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/hashlib.py", line 139, in <module>  
    globals()[__func_name] = __get_hash(__func_name)  
  File "/home/yoann/Softwares/longislnd/sampling_example/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor  
    raise ValueError('unsupported hash type %s' % name)  
ValueError: unsupported hash type sha224  
ERROR:root:code for hash sha256 was not found.  
Traceback (most recent call last):  
  File "/home/yoann/Softwares/longislnd/sampling_example/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/hashlib.py", line 139, in <module>  
    globals()[__func_name] = __get_hash(__func_name)  
  File "/home/yoann/Softwares/longislnd/sampling_example/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor  
    raise ValueError('unsupported hash type %s' % name)  
ValueError: unsupported hash type sha256  
ERROR:root:code for hash sha384 was not found.  
Traceback (most recent call last):  
  File "/home/yoann/Softwares/longislnd/sampling_example/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/hashlib.py", line 139, in <module>  
    globals()[__func_name] = __get_hash(__func_name)  
  File "/home/yoann/Softwares/longislnd/sampling_example/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor  
    raise ValueError('unsupported hash type %s' % name)  
ValueError: unsupported hash type sha384  
ERROR:root:code for hash sha512 was not found.  
Traceback (most recent call last):  
  File "/home/yoann/Softwares/longislnd/sampling_example/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/hashlib.py", line 139, in <module>  
    globals()[__func_name] = __get_hash(__func_name)  
  File "/home/yoann/Softwares/longislnd/sampling_example/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor  
    raise ValueError('unsupported hash type %s' % name)  
ValueError: unsupported hash type sha512  
Traceback (most recent call last):  
  File "bin/conf_main.py", line 4, in <module>  
    from bin.util.upgradeUtil import *  
  File "/home/yoann/Softwares/longislnd/sampling_example/smrtanalysis/install/smrtanalysis_2.3.0.140936/etc/scripts/postinstall/bin/util/upgradeUtil.py", line 16, in <module>  
    from fabric.api import *  
  File "/home/yoann/Softwares/longislnd/sampling_example/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/fabric/api.py", line 9, in <module>  
    from fabric.context_managers import (cd, hide, settings, show, path, prefix,  
  File "/home/yoann/Softwares/longislnd/sampling_example/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/fabric/context_managers.py", line 42, in <module>  
    from fabric.state import output, win32, connections, env  
  File "/home/yoann/Softwares/longislnd/sampling_example/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/fabric/state.py", line 9, in <module>  
    from fabric.network import HostConnectionCache, ssh  
  File "/home/yoann/Softwares/longislnd/sampling_example/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/fabric/network.py", line 24, in <module>  
    import paramiko as ssh  
  File "/home/yoann/Softwares/longislnd/sampling_example/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/paramiko/__init__.py", line 64, in <module>  
    from transport import SecurityOptions, Transport  
  File "/home/yoann/Softwares/longislnd/sampling_example/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/paramiko/transport.py", line 38, in <module>  
    from paramiko.dsskey import DSSKey  
  File "/home/yoann/Softwares/longislnd/sampling_example/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/paramiko/dsskey.py", line 23, in <module>  
    from Crypto.PublicKey import DSA  
  File "/home/yoann/Softwares/longislnd/sampling_example/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/Crypto/PublicKey/DSA.py", line 33, in <module>  
    from Crypto.PublicKey import _DSA, _slowmath, pubkey  
  File "/home/yoann/Softwares/longislnd/sampling_example/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/Crypto/PublicKey/_DSA.py", line 33, in <module>  
    from Crypto.Hash import SHA  
  File "/home/yoann/Softwares/longislnd/sampling_example/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/Crypto/Hash/SHA.py", line 32, in <module>  
    digest_size = new().digest_size  
  File "/home/yoann/Softwares/longislnd/sampling_example/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/Crypto/Hash/SHA.py", line 31, in new  
    return hashlib.sha1(data)  
AttributeError: 'module' object has no attribute 'sha1'  
installprompter: Error! Encountered unexpected error at 'line 3530 /home/yoann/Softwares/longislnd/sampling_example/smrtanalysis/install/smrtanalysis_2.3.0.140936/admin/bin/installprompter', bailing out...
```

Do you know what happen here and how to solve the issue ?

**Comment by bayolau** [comment]
Thank you very much for your interest. We're having a bit of problem reproducing this, as it seems to be a system-related problem. What OS are you running on, and what is the system `python`?

**Comment by yoann-dufresne** [comment]
I'm running on ubuntu 18.04 with python 3.6.5

**Comment by yoann-dufresne** [comment]
The error seems related to libssl.
However libssl1.0.0 is already installed on the computer

**Comment by bayolau** [comment]
https://stackoverflow.com/questions/11433108/unsupported-hash-type-when-installing-plone
